### PR TITLE
refactor: use internal functions

### PR DESCRIPTION
**Pull request by sadeghbarati**
Hi, thanks for Svelte Legos

This PR does not have much impact 😃 just followed DRY principles

### CODE REVIEW

**Comment by ankurrsinghal** [comment]
Wow this is amazing, thank you so much @sadeghbarati, I just checked few of the files changed, I will fully review it and merge this asap.

**Comment by sadeghbarati** [comment]
Probably you saw this shared utils like

- isString
- isNumber
- isFunction 
- isObject
- isArray
- isMap
- isSet
- isSymbol
- debounce
- throttle
- hasOwnProperty
- noop
- ....

These same functions exist in some libraries cause they want their package to be dependency-free, and I agree with it, it should

 But I think Bundlers can't recognize these functions are the same, cause these are imported from different modules
 

---

Let me explain the main reason by Vue and VueUse example

I want to create Vue package, some utils that I need exist in `vue/shared`, and some of them are in `vueuse/shared`

Vue is in my dependencies so I can use their shared modules without duplicating the same code
But users may not have installed VueUse in their dependencies in this case

- I can duplicate their code or write a compact version of it
- or I can use export conditions in package.json

```package.json
"exports": {
    ".": "./dist/index.mjs",
    "./with-vueuse": "./dist/with-vueuse.mjs",
}
```

and check if vueuse module exist with `postinstall` script change `package.json` main entry to `with-vueuse.mjs`

**Review by ankurrsinghal — APPROVED** [review]

**Comment by ankurrsinghal** [comment]
This is really good. Thanks @sadeghbarati.

**Comment by jalavosus** [comment]
@ankurrsinghal This PR broke all compatibility with Svelte 5, please consider reverting it.

**Pull request merged**
