### PR TITLE
Add clickToShareAction

### PR DESCRIPTION
**Pull request by rossrobino**
Add a clickToShareAction

### CODE REVIEW

**Comment by rossrobino** [comment]
This PR adds the `navigator.share` API as an action. This is an easier user experience given browser support, especially on mobile devices.

`navigator.canShare` can be used to determine if the browser supports the `navigator.share` method.

```svelte
{#if navigator.canShare}
    <button use:clickToShareAction={{ text, title, url }}>
        Click to share
    </button>
{/if}
```

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by rossrobino** [comment]
@ankurrsinghal Would it be possible to call the `clickToCopyAction` as a backup?

**Comment by ankurrsinghal** [comment]
Hey @rossrobino I will check this and get back to you later. Have a lot pending actions and utilities on plate.

**Comment by rossrobino** [comment]
@ankurrsinghal I can work on it I'll see what I come up with.

**Review by ankurrsinghal — APPROVED** [review]

**Pull request merged**
